sdk: streamlit
app_file: app.py
title: "LineSmart Technician Training Generator"
emoji: 📘
color_from: blue
color_to: green
sdk: streamlit
app_file: app.py
title: "LineSmart Technician Training Generator"
emoji: 📘
color_from: blue
color_to: green
sdk: streamlit
app_file: app.py
title: "LineSmart Technician Training Generator"
emoji: 📘
color_from: blue
color_to: green